In [2]:
import numpy as np
a = np.random.rand(8,13,13)
print(a)

[[[0.61928883 0.83020492 0.86969803 ... 0.26305303 0.70785257 0.93974279]
  [0.96258534 0.03692685 0.89302638 ... 0.99123079 0.51198944 0.81564392]
  [0.63844363 0.23345737 0.55097063 ... 0.01523615 0.44830873 0.40510159]
  ...
  [0.94423336 0.41394972 0.98275707 ... 0.7756493  0.59112655 0.71722998]
  [0.06365213 0.18035158 0.61731719 ... 0.02036146 0.6528497  0.59343608]
  [0.98832056 0.81940733 0.68593708 ... 0.01364568 0.67403884 0.80396043]]

 [[0.72681667 0.58110132 0.25289146 ... 0.05715272 0.3690677  0.30674241]
  [0.03413433 0.34034672 0.59886679 ... 0.27488663 0.91445457 0.33500965]
  [0.20563311 0.13027312 0.73417564 ... 0.81298141 0.69889472 0.41917604]
  ...
  [0.91756764 0.37178005 0.68701503 ... 0.80328343 0.12559965 0.84839766]
  [0.43947692 0.52248001 0.06752944 ... 0.75118847 0.73083776 0.79731707]
  [0.2907075  0.88668867 0.03242552 ... 0.51429239 0.45177595 0.48653708]]

 [[0.36447276 0.99980548 0.86995622 ... 0.3661167  0.49539499 0.51765915]
  [0.4885347  0.215686

In [8]:
a = np.random.rand(3,2)
b = np.random.rand(3,2)
print(a)
print(b)
c= np.dot(np.transpose(a),b)
print(c)

[[0.92443864 0.14340397]
 [0.41837645 0.95353981]
 [0.09921655 0.79087072]]
[[0.54009752 0.26020129]
 [0.72410047 0.90956503]
 [0.5140028  0.49255961]]
[[0.85323119 0.66995078]
 [1.17442052 1.29417135]]


In [25]:
a = np.array([[[1, 2, 3], [2, 1, 3]],[[2, 1, 0], [2, 4, 1]]])
b = np.array([[[2, 1, 1], [2, 4, 0]],[[2, 1, 4], [2, 1, 3]]])
b1 = b.reshape(2, 3, 2)
#c = a @ b
print(b1)
print("----")
c = np.dot(a,b1)
print(c,c.shape)
print("----")
d= a @ b1
print(d,d.shape)

[[[2 1]
  [1 2]
  [4 0]]

 [[2 1]
  [4 2]
  [1 3]]]
----
[[[[16  5]
   [13 14]]

  [[17  4]
   [11 13]]]


 [[[ 5  4]
   [ 8  4]]

  [[12 10]
   [21 13]]]] (2, 2, 2, 2)
----
[[[16  5]
  [17  4]]

 [[ 8  4]
  [21 13]]] (2, 2, 2)


In [26]:
a = np.array([[[1, 2, 3], [2, 1, 3]]])
b = np.array([[[2, 1, 1], [2, 4, 0]]])
b1 = b.reshape(1, 3, 2)
d= a @ b1
print(b1)
print("====")
print(d)

[[[2 1]
  [1 2]
  [4 0]]]
====
[[[16  5]
  [17  4]]]
